function A (){
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa

//AAAAAAAAAAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAAAAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAAAAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAAAAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAAAAAAAAAA
//AAAAAAAAAAAAAAAA


}


function B() {

}