function A (){
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa
//AAAAAAAA
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAa

}


function B() {

}